[package]
name = "peg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.9.2"
thiserror = "1.0.40"
tracing = "0.1.37"
unescape = "0.1.0"

[dev-dependencies]
tracing-subscriber = "0.3.16"
